import type { Metadata } from "next";
import { Lato, Montserrat, Archivo, League_Spartan } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const primaryFont = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-lato",
});
const secondaryFont = League_Spartan({
  subsets: ["latin"],
  variable: "--font-league-spartan",
});
// const secondaryFont = Montserrat({
//   subsets: ["latin"],
//   variable: "--font-montserrat",
// });
const accentFont = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className=' h-full overflow-hidden'>
      <body
        className={`${primaryFont.variable} ${secondaryFont.variable} ${accentFont.variable} h-[100vh] relative`}
      >
        <Header />
        <main className='pt-header flex flex-col'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}

const palette = {
  blue: "#0c5788",
  gray: "#a6a6a6",
  lgihtGray1: "#ebebeb",
  lgihtGray2: "#fafafa",
  accent: "#c1e1de",
  black: "#3f3e3e",
};
